import { Project } from './types';

const svgToDataUri = (svg: string) => `data:image/svg+xml;charset=utf-8,${encodeURIComponent(svg)}`;

const svgDesigns = [
  // Design 1: Monochrome Waves
  `<svg viewBox="0 0 400 400" xmlns="http://www.w3.org/2000/svg"><defs><linearGradient id="g1" x1="0%" y1="0%" x2="100%" y2="100%"><stop offset="0%" stop-color="#000000"/><stop offset="100%" stop-color="#9ca3af"/></linearGradient></defs><rect width="400" height="400" fill="#f9fafb"/><path d="M0 200 C 100 100, 300 300, 400 200" stroke="url(#g1)" stroke-width="3" fill="none" opacity="0.6"/><path d="M0 250 C 150 180, 250 320, 400 250" stroke="url(#g1)" stroke-width="2" fill="none" opacity="0.4"/></svg>`,
  // Design 2: Geo Grid
  `<svg viewBox="0 0 400 400" xmlns="http://www.w3.org/2000/svg"><defs><linearGradient id="g2" x1="100%" y1="0%" x2="0%" y2="100%"><stop offset="0%" stop-color="#000000"/><stop offset="100%" stop-color="#d1d5db"/></linearGradient></defs><rect width="400" height="400" fill="#f9fafb"/><g transform="rotate(45 200 200)" opacity="0.5"><rect x="100" y="100" width="200" height="200" fill="none" stroke="url(#g2)" stroke-width="4" rx="2"/></g><g transform="rotate(-30 200 200)" opacity="0.3"><rect x="125" y="125" width="150" height="150" fill="none" stroke="url(#g2)" stroke-width="2" rx="1"/></g></svg>`,
  // Design 3: Minimal Nebula
  `<svg viewBox="0 0 400 400" xmlns="http://www.w3.org/2000/svg"><defs><filter id="f1"><feGaussianBlur in="SourceGraphic" stdDeviation="50" /></filter><radialGradient id="g3" cx="50%" cy="50%" r="50%"><stop offset="0%" stop-color="#000000" stop-opacity="0.3"/><stop offset="100%" stop-color="#f9fafb" stop-opacity="0"/></radialGradient></defs><rect width="400" height="400" fill="#f9fafb"/><circle cx="200" cy="200" r="200" fill="url(#g3)" filter="url(#f1)"/></svg>`,
  // Design 4: Architecture
  `<svg viewBox="0 0 400 400" xmlns="http://www.w3.org/2000/svg"><defs><pattern id="p1" width="20" height="20" patternUnits="userSpaceOnUse"><path d="M0 10 h20 M10 0 v20" stroke="#000000" stroke-width="0.5" fill="none" opacity="0.1"/></pattern></defs><rect width="400" height="400" fill="#f9fafb"/><rect width="400" height="400" fill="url(#p1)"/><path d="M50 50 L350 350 M350 50 L50 350" stroke="#000000" stroke-width="1" opacity="0.05"/></svg>`,
];


const getImageForIndex = (index: number) => {
  return svgToDataUri(svgDesigns[index % svgDesigns.length]);
};


export const PROJECTS: Project[] = [
  {
    id: 39,
    title: 'Popnants 500 App MVPs',
    description: 'A curated collection of vibe-coded MVP applications showcasing innovative design patterns, interactive experiences, and modern development practices across FinTech, EdTech, AgriTech, AI Startups, and Web3.',
    imageUrl: getImageForIndex(0),
    url: 'https://vibelanding-z9xjgdag.manus.space/',
    tags: ['MVP', 'Showcase', 'Vibe-coded', 'Portfolio', 'Multi-Industry'],
    category: 'SaaS & Platforms',
    createdAt: '2025-02-21',
  },
  {
    id: 38,
    title: 'Kazira.io Clinical Intelligence MVP',
    description: 'An advanced AI-powered platform for clinical data analysis and intelligence, designed to streamline healthcare decision-making through synthesized diagnostic insights.',
    imageUrl: getImageForIndex(1),
    url: 'https://kazira-io-clinical-intelligence-mvp.vercel.app/',
    tags: ['AI', 'Healthcare', 'Clinical Intelligence', 'SaaS', 'Data Analytics'],
    category: 'AI/ML',
    createdAt: '2025-02-19',
  },
  {
    id: 37,
    title: 'Oral Biohacker AI V2',
    description: 'The advanced evolution of oral biohacking. Features deeper biometric analysis, personalized habit coaching, and intelligent diagnostic insights.',
    imageUrl: getImageForIndex(2),
    url: 'https://oral-biohacker-ai-v2.vercel.app/',
    tags: ['AI', 'Health', 'Biohacking', 'Gemini', 'Wellness', 'V2.0'],
    category: 'AI/ML',
    createdAt: '2025-02-15',
  },
  {
    id: 31,
    title: 'Oral Biohacker AI',
    description: 'Hack your oral and systemic health with AI-driven insights, biometrics, and personalized habit design.',
    imageUrl: getImageForIndex(0),
    url: 'https://oral-bio-ai.vercel.app/',
    tags: ['AI', 'Health', 'Biohacking', 'Biometrics', 'Wellness'],
    category: 'AI/ML',
    createdAt: '2024-08-10',
  },
  {
    id: 36,
    title: 'Portfolio Net Worth Calculator',
    description: 'A comprehensive AI-crafted tool to track and visualize your total net worth across different asset classes with interactive charts.',
    imageUrl: getImageForIndex(3),
    url: 'https://claude.ai/public/artifacts/7792809c-beef-495a-903e-f7ecee0983d9',
    tags: ['Fintech', 'Portfolio', 'Net Worth', 'Calculator', 'Visualization'],
    category: 'Fintech & Crypto',
    createdAt: '2024-11-21',
  },
  {
    id: 35,
    title: 'Portfolio Rebalancing Calculator',
    description: 'Enter your current portfolio values, customize your target allocation, and add new asset classes to get personalized rebalancing recommendations.',
    imageUrl: getImageForIndex(0),
    url: 'https://rebalancecalc-qiyampwr.manus.space/',
    tags: ['Fintech', 'Portfolio', 'Investment', 'Calculator', 'Wealth Management'],
    category: 'Fintech & Crypto',
    createdAt: '2024-11-20',
  },
  {
    id: 34,
    title: 'MedAssure KE',
    description: 'An AI-driven compliance intelligence platform for Kenyan medical practitioners and facilities, automating regulatory tracking with KMPDC, PPB, and NEMA.',
    imageUrl: getImageForIndex(2),
    url: 'https://med-assure-ke.vercel.app/',
    tags: ['Health', 'AI', 'Compliance', 'Kenya', 'SaaS'],
    category: 'SaaS & Platforms',
    createdAt: '2024-10-26',
  },
  {
    id: 33,
    title: 'Lugha Learner OS',
    description: 'Kenyan language learning operating system for linguistic data collection.',
    imageUrl: getImageForIndex(1),
    url: 'https://lugha-learner-os.vercel.app/',
    tags: ['Language', 'Kenya', 'Data Collection', 'OS', 'Education'],
    category: 'Civic & EdTech',
    createdAt: '2024-09-01',
  },
  {
    id: 32,
    title: 'OHIP (Oral Health Intelligence Platform)',
    description: 'A comprehensive platform utilizing advanced intelligence for oral health monitoring, diagnostics, and personalized care insights.',
    imageUrl: getImageForIndex(3),
    url: 'https://ohip-sigma.vercel.app/',
    tags: ['Health', 'AI', 'Oral Health', 'Platform', 'Diagnostics'],
    category: 'AI/ML',
    createdAt: '2024-08-15',
  },
  {
    id: 101,
    title: 'Lugha Learner',
    description: 'An intelligent language learning assistant for Kenyan languages, powered by AI.',
    imageUrl: getImageForIndex(2),
    url: 'https://lugha-learner.vercel.app/',
    tags: ['AI', 'Language', 'Kenya', 'Education'],
    category: 'Civic & EdTech',
    createdAt: '2024-03-10',
  },
  {
    id: 22,
    title: 'Lugha Learner Kenya (Version 2.0)',
    description: 'The next generation AI-powered assistant for learning Kenyan languages, featuring new lessons and an improved user experience.',
    imageUrl: getImageForIndex(0),
    url: 'https://lugha-learner-lovable-kenya.lovable.app/',
    tags: ['AI', 'Language', 'Kenya', 'Education', 'V2.0'],
    category: 'Civic & EdTech',
    createdAt: '2024-06-20',
  },
  {
    id: 24,
    title: 'Kazira.io',
    description: 'A modern SaaS platform by Kazira.io providing AI-powered automation (Kazira Automate) and future-skills learning (Kazira Learn).',
    imageUrl: getImageForIndex(3),
    url: 'https://kazira-io.vercel.app/',
    tags: ['SaaS', 'AI', 'Automation', 'EdTech'],
    category: 'SaaS & Platforms',
    createdAt: '2024-06-28',
  },
  {
    id: 100,
    title: 'Mwakilishi Wangu',
    description: 'A platform connecting Kenyan citizens with their elected representatives for enhanced civic engagement.',
    imageUrl: getImageForIndex(3),
    url: 'https://mwakilishi-wangu.vercel.app/',
    tags: ['Civic Tech', 'Kenya', 'Governance'],
    category: 'Civic & EdTech',
    createdAt: '2024-01-28',
  },
  {
    id: 30,
    title: 'Google Canvas Compositions',
    description: 'AI-powered image style reference generators using Google Canvas to inspire creative projects.',
    imageUrl: getImageForIndex(1),
    url: 'https://google-canvas-compos-rqcc.bolt.host/',
    tags: ['AI', 'Google Canvas', 'Image Generation', 'Art', 'Style Reference'],
    category: 'AI/ML',
    createdAt: '2024-07-25',
  },
  {
    id: 29,
    title: 'Cinema AI Agent Bot',
    description: 'An AI-powered agent to help you discover books, cinema, and movies.',
    imageUrl: getImageForIndex(1),
    url: 'https://cinema-agent.vercel.app/',
    tags: ['AI', 'Agent', 'Cinema', 'Movies', 'Bot'],
    category: 'AI/ML',
    createdAt: '2024-07-23',
  },
  {
    id: 28,
    title: 'kazira.io SaaS',
    description: 'A modern SaaS platform focusing on the future of work, offering intelligent AI solutions to boost efficiency and innovation.',
    imageUrl: getImageForIndex(0),
    url: 'https://kazira-io-saas-landi-3e55.bolt.host/',
    tags: ['SaaS', 'AI', 'Future of Work', 'Innovation'],
    category: 'SaaS & Platforms',
    createdAt: '2024-07-21',
  },
  {
    id: 27,
    title: 'BTC - Mpesa Demo',
    description: 'A web application that allows users to spend Bitcoin via M-Pesa by converting BTC to KES and sending it to a specified M-Pesa recipient (Phone Number, Paybill, or Till Number).',
    imageUrl: getImageForIndex(2),
    url: 'https://btc-mpesa.vercel.app/',
    tags: ['Bitcoin', 'M-Pesa', 'Fintech', 'Kenya', 'Crypto'],
    category: 'Fintech & Crypto',
    createdAt: '2024-07-10',
  },
  {
    id: 26,
    title: 'Stylo - AI wardrobe transformer',
    description: 'An AI-powered application that transforms your wardrobe by suggesting new outfits, cataloging your clothes, and helping you discover your personal style.',
    imageUrl: getImageForIndex(1),
    url: 'https://stylo-sooty.vercel.app/',
    tags: ['AI', 'Fashion', 'Style', 'Wardrobe', 'Assistant'],
    category: 'AI/ML',
    createdAt: '2024-07-05',
  },
  {
    id: 25,
    title: 'nanoStrategyKE AI Accelerator Challenge',
    description: 'A web application to display the 28-Day AI Accelerator course, designed to help users master productivity and creativity with AI tools. The app presents the course structure, modules, daily lessons, and learning objectives in an engaging format.',
    imageUrl: getImageForIndex(0),
    url: 'https://nanostrategy-ke.vercel.app/',
    tags: ['AI', 'Education', 'Productivity', 'Course'],
    category: 'Civic & EdTech',
    createdAt: '2024-07-01',
  },
  {
    id: 23,
    title: 'Crave Cam',
    description: 'An AI-powered Restaurant Reels app that creates stunning short videos for your culinary creations, perfect for social media marketing.',
    imageUrl: getImageForIndex(2),
    url: 'https://crave-cam-v2.vercel.app/',
    tags: ['AI', 'Video', 'Food', 'Marketing'],
    category: 'Creative & Media',
    createdAt: '2024-06-25',
  },
  {
    id: 21,
    title: 'Safari Mate - AI Travel Agent',
    description: 'An AI-powered travel assistant that helps travelers prepare for trips by providing a personalized checklist of requirements to avoid any hiccups.',
    imageUrl: getImageForIndex(1),
    url: 'https://safari-mate-ecru.vercel.app/',
    tags: ['AI', 'Travel', 'Assistant', 'Planning'],
    category: 'AI/ML',
    createdAt: '2024-06-18',
  },
  {
    id: 20,
    title: 'KRA Tax Tools - Annual Calculator & WHT Tracker',
    description: 'Includes a Kenyan Individual Annual Income Tax Calculator and a Withholding Tax (WHT) Tracker with an option to upload WHT certificates for information extraction (experimental).',
    imageUrl: getImageForIndex(0),
    url: 'https://tax-calculator-henna-seven.vercel.app/',
    tags: ['Fintech', 'Tax', 'Kenya', 'Calculator'],
    category: 'Fintech & Crypto',
    createdAt: '2024-06-15',
  },
  {
    id: 19,
    title: 'KaziraX Automate - Future of Work',
    description: 'KaziraX Automate offers intelligent AI solutions to augment and replace declining job roles, boosting efficiency and innovation for businesses.',
    imageUrl: getImageForIndex(1),
    url: 'https://kazira-x.vercel.app/',
    tags: ['AI', 'Automation', 'Future of Work', 'SaaS'],
    category: 'SaaS & Platforms',
    createdAt: '2024-06-12',
  },
  {
    id: 102,
    title: 'Kenya MedReg Compliance Assistant',
    description: 'A centralized platform to manage and track medical compliance documentation and reporting.',
    imageUrl: getImageForIndex(3),
    url: 'https://kenya-med-reg-compliance.vercel.app/',
    tags: ['Health', 'Compliance', 'SaaS'],
    category: 'SaaS & Platforms',
    createdAt: '2024-03-08',
  },
  {
    id: 16,
    title: 'Networth Portfolio Tracker',
    description: 'A comprehensive tool to track and manage your net worth and investment portfolios in real-time.',
    imageUrl: getImageForIndex(1),
    url: 'https://net-worth-portfolio-tracker.vercel.app/',
    tags: ['Fintech', 'Portfolio', 'Tracker', 'Investment'],
    category: 'Fintech & Crypto',
    createdAt: '2024-02-05',
  },
  {
    id: 17,
    title: 'KenyaBase Company Explorer',
    description: 'An interactive tool to explore and analyze comprehensive data on Kenyan companies.',
    imageUrl: getImageForIndex(0),
    url: 'https://kenyabase-i1bb.vercel.app/',
    tags: ['Kenya', 'Business', 'Data', 'Analytics'],
    category: 'SaaS & Platforms',
    createdAt: '2024-02-01',
  },
  {
    id: 4,
    title: 'LandChain Africa',
    description: 'A blockchain-based solution for secure land registry in Africa.',
    imageUrl: getImageForIndex(3),
    url: 'https://land-chain-africa.vercel.app/',
    tags: ['Blockchain', 'Real Estate', 'Web3'],
    category: 'Web3 & Blockchain',
    createdAt: '2023-12-22',
  },
  {
    id: 5,
    title: 'Agile Learning Ecosystem',
    description: 'A platform to facilitate agile and collaborative learning environments.',
    imageUrl: getImageForIndex(0),
    url: 'https://replit.com/@eltonarunga/AgileLearningEcosystem',
    tags: ['Education', 'Agile', 'Collaboration'],
    category: 'Civic & EdTech',
    createdAt: '2023-12-20',
  },
  {
    id: 8,
    title: 'Art chain',
    description: 'A vibrant marketplace for buying, selling, and discovering unique digital art and collectibles.',
    imageUrl: getImageForIndex(3),
    url: 'https://art-chain-opal.vercel.app/',
    tags: ['Art', 'Marketplace', 'Web3'],
    category: 'Web3 & Blockchain',
    createdAt: '2023-11-18',
  },
  {
    id: 9,
    title: 'Vibe codes',
    description: 'A collection of creative and aesthetically pleasing coding projects.',
    imageUrl: getImageForIndex(0),
    url: 'https://vibecodes-wbkwyjej.manus.space',
    tags: ['Creative Coding', 'Portfolio', 'Art'],
    category: 'Creative & Media',
    createdAt: '2023-11-15',
  },
  {
    id: 11,
    title: 'Mining Dashboard',
    description: 'A real-time dashboard to monitor and manage industrial mining operations.',
    imageUrl: getImageForIndex(2),
    url: 'https://aeejbufd.manus.space/',
    tags: ['Industrial', 'Dashboard', 'Operations', 'Real-time'],
    category: 'SaaS & Platforms',
    createdAt: '2023-10-12',
  },
  {
    id: 12,
    title: 'Kazira.io Job Disruption Scanner (Opal)',
    description: 'An innovative agent built on the Opal platform, designed for intelligent task automation and assistance.',
    imageUrl: getImageForIndex(3),
    url: 'https://opal.withgoogle.com/?flow=drive:/1g5EsPt18QZYsNAcaE1f9KgmCnWOQEvin&shared&mode=app',
    tags: ['AI', 'Agent', 'Opal', 'Automation'],
    category: 'AI/ML',
    createdAt: '2023-10-10',
  },
  {
    id: 13,
    title: 'AgriProof X',
    description: 'A comprehensive agricultural platform that combines AI, blockchain, and DeFi to empower farmers with asset verification, intelligent farming assistance, microfinance access, supply chain tracking, and a community marketplace.',
    imageUrl: getImageForIndex(0),
    url: 'https://app--agri-proof-x-1936b50a.base44.app',
    tags: ['AI', 'Blockchain', 'DeFi', 'Agriculture', 'Fintech'],
    category: 'Fintech & Crypto',
    createdAt: '2023-09-08',
  },
  {
    id: 14,
    title: 'Cheffie Ai',
    description: 'An AI-powered agent to streamline your food ordering experience, making it faster and more intuitive.',
    imageUrl: getImageForIndex(1),
    url: 'https://cheffie.vercel.app/',
    tags: ['AI', 'Agent', 'Food', 'Automation'],
    category: 'AI/ML',
    createdAt: '2023-09-05',
  },
  {
    id: 15,
    title: 'Suno Compositions',
    description: 'AI-powered music and audio compositions exploring the frontiers of generative art.',
    imageUrl: getImageForIndex(2),
    url: 'https://suno.com/@earunga',
    tags: ['AI', 'Music', 'Audio', 'Generative'],
    category: 'Creative & Media',
    createdAt: '2023-08-01',
  }
];